# Generated by Django 4.2.8 on 2024-01-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='price',
            new_name='year',
        ),
    ]
